name: breez_sdk_spark_flutter
description: Flutter bindings for the Breez Spark SDK
version: 0.7.2
homepage: https://breez.technology
repository: https://github.com/breez/breez-sdk-spark-flutter
publish_to: 'none'

environment:
  sdk: '>=3.7.0 <4.0.0' # ffi: 2.1.4 requires Dart 3.7.0 or greater 
  flutter: ">=3.27.0"

dev_dependencies:
  build_runner: ^2.4.15
  ffigen: ^18.0.0
  freezed: ^3.0.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dependencies:
  ffi: ^2.1.4
  flutter_rust_bridge: 2.9.0
  freezed_annotation: ^3.0.0
  logging: ^1.3.0
  meta: ^1.16.0
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true